/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ComoPuedoAcompanarteRouteImport } from './routes/como-puedo-acompanarte'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as LimpiezasEnergeticasRouteImport } from './routes/limpiezas-energeticas'
import { Route as MediumnidadRouteImport } from './routes/mediumnidad'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as YogaRouteImport } from './routes/yoga'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPuedoAcompanarteRoute = ComoPuedoAcompanarteRouteImport.update({
  id: '/como-puedo-acompanarte',
  path: '/como-puedo-acompanarte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpiezasEnergeticasRoute = LimpiezasEnergeticasRouteImport.update({
  id: '/limpiezas-energeticas',
  path: '/limpiezas-energeticas',
  getParentRoute: () => rootRouteImport,
} as any)
const MediumnidadRoute = MediumnidadRouteImport.update({
  id: '/mediumnidad',
  path: '/mediumnidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/sobre-mi'
    | '/yoga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/sobre-mi'
    | '/yoga'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/sobre-mi'
    | '/yoga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ComoPuedoAcompanarteRoute: typeof ComoPuedoAcompanarteRoute
  ContactoRoute: typeof ContactoRoute
  HerramientasRoute: typeof HerramientasRoute
  LimpiezasEnergeticasRoute: typeof LimpiezasEnergeticasRoute
  MediumnidadRoute: typeof MediumnidadRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  SobreMiRoute: typeof SobreMiRoute
  YogaRoute: typeof YogaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-puedo-acompanarte': {
      id: '/como-puedo-acompanarte'
      path: '/como-puedo-acompanarte'
      fullPath: '/como-puedo-acompanarte'
      preLoaderRoute: typeof ComoPuedoAcompanarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpiezas-energeticas': {
      id: '/limpiezas-energeticas'
      path: '/limpiezas-energeticas'
      fullPath: '/limpiezas-energeticas'
      preLoaderRoute: typeof LimpiezasEnergeticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediumnidad': {
      id: '/mediumnidad'
      path: '/mediumnidad'
      fullPath: '/mediumnidad'
      preLoaderRoute: typeof MediumnidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ComoPuedoAcompanarteRoute: ComoPuedoAcompanarteRoute,
  ContactoRoute: ContactoRoute,
  HerramientasRoute: HerramientasRoute,
  LimpiezasEnergeticasRoute: LimpiezasEnergeticasRoute,
  MediumnidadRoute: MediumnidadRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  SobreMiRoute: SobreMiRoute,
  YogaRoute: YogaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
