/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ComoPuedoAcompanarteRouteImport } from './routes/como-puedo-acompanarte'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as LimpiezasEnergeticasRouteImport } from './routes/limpiezas-energeticas'
import { Route as MediumnidadRouteImport } from './routes/mediumnidad'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as RetirosRouteImport } from './routes/retiros'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPuedoAcompanarteRoute = ComoPuedoAcompanarteRouteImport.update({
  id: '/como-puedo-acompanarte',
  path: '/como-puedo-acompanarte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpiezasEnergeticasRoute = LimpiezasEnergeticasRouteImport.update({
  id: '/limpiezas-energeticas',
  path: '/limpiezas-energeticas',
  getParentRoute: () => rootRouteImport,
} as any)
const MediumnidadRoute = MediumnidadRouteImport.update({
  id: '/mediumnidad',
  path: '/mediumnidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirosRoute = RetirosRouteImport.update({
  id: '/retiros',
  path: '/retiros',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/retiros': typeof RetirosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/retiros': typeof RetirosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-puedo-acompanarte': typeof ComoPuedoAcompanarteRoute
  '/contacto': typeof ContactoRoute
  '/herramientas': typeof HerramientasRoute
  '/limpiezas-energeticas': typeof LimpiezasEnergeticasRoute
  '/mediumnidad': typeof MediumnidadRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/retiros': typeof RetirosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-privacidad'
    | '/retiros'
    | '/sobre-mi'
    | '/yoga'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-privacidad'
    | '/retiros'
    | '/sobre-mi'
    | '/yoga'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/como-puedo-acompanarte'
    | '/contacto'
    | '/herramientas'
    | '/limpiezas-energeticas'
    | '/mediumnidad'
    | '/politica-de-privacidad'
    | '/retiros'
    | '/sobre-mi'
    | '/yoga'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoPuedoAcompanarteRoute: typeof ComoPuedoAcompanarteRoute
  ContactoRoute: typeof ContactoRoute
  HerramientasRoute: typeof HerramientasRoute
  LimpiezasEnergeticasRoute: typeof LimpiezasEnergeticasRoute
  MediumnidadRoute: typeof MediumnidadRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  RetirosRoute: typeof RetirosRoute
  SobreMiRoute: typeof SobreMiRoute
  YogaRoute: typeof YogaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-puedo-acompanarte': {
      id: '/como-puedo-acompanarte'
      path: '/como-puedo-acompanarte'
      fullPath: '/como-puedo-acompanarte'
      preLoaderRoute: typeof ComoPuedoAcompanarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpiezas-energeticas': {
      id: '/limpiezas-energeticas'
      path: '/limpiezas-energeticas'
      fullPath: '/limpiezas-energeticas'
      preLoaderRoute: typeof LimpiezasEnergeticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediumnidad': {
      id: '/mediumnidad'
      path: '/mediumnidad'
      fullPath: '/mediumnidad'
      preLoaderRoute: typeof MediumnidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiros': {
      id: '/retiros'
      path: '/retiros'
      fullPath: '/retiros'
      preLoaderRoute: typeof RetirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoPuedoAcompanarteRoute: ComoPuedoAcompanarteRoute,
  ContactoRoute: ContactoRoute,
  HerramientasRoute: HerramientasRoute,
  LimpiezasEnergeticasRoute: LimpiezasEnergeticasRoute,
  MediumnidadRoute: MediumnidadRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  RetirosRoute: RetirosRoute,
  SobreMiRoute: SobreMiRoute,
  YogaRoute: YogaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
